function(platformer_normalize_ios_sdk input_var output_var)
  if(NOT DEFINED ${input_var})
    set(${output_var} "" PARENT_SCOPE)
    return()
  endif()

  set(_sdk_value "${${input_var}}")
  if(_sdk_value STREQUAL "")
    set(${output_var} "" PARENT_SCOPE)
    return()
  endif()

  string(TOLOWER "${_sdk_value}" _sdk_lower)
  if(_sdk_lower MATCHES "iphonesimulator")
    set(${output_var} "iphonesimulator" PARENT_SCOPE)
  elseif(_sdk_lower MATCHES "iphoneos")
    set(${output_var} "iphoneos" PARENT_SCOPE)
  else()
    set(${output_var} "${_sdk_value}" PARENT_SCOPE)
  endif()
endfunction()
