if(NOT DEFINED MANIFEST_FILE OR MANIFEST_FILE STREQUAL "")
  message(FATAL_ERROR "MANIFEST_FILE is required")
endif()
if(NOT EXISTS "${MANIFEST_FILE}")
  message(FATAL_ERROR "iOS package manifest does not exist: ${MANIFEST_FILE}")
endif()
if(NOT DEFINED APP_NAME OR APP_NAME STREQUAL "")
  set(APP_NAME "platformer")
endif()
if(NOT DEFINED EXPECTED_IOS_SDK)
  set(EXPECTED_IOS_SDK "")
endif()
if(NOT DEFINED EXPECTED_IOS_ARCHS)
  set(EXPECTED_IOS_ARCHS "")
endif()
if(NOT DEFINED EXPECTED_IOS_CODE_SIGNING_REQUIRED)
  set(EXPECTED_IOS_CODE_SIGNING_REQUIRED "")
endif()
if(NOT DEFINED EXPECTED_IOS_BUNDLE_IDENTIFIER)
  set(EXPECTED_IOS_BUNDLE_IDENTIFIER "")
endif()
if(NOT DEFINED EXPECTED_IOS_MINIMUM_OS_VERSION)
  set(EXPECTED_IOS_MINIMUM_OS_VERSION "")
endif()
if(NOT DEFINED EXPECTED_REQUIRED_BUNDLE_ENTRIES)
  set(EXPECTED_REQUIRED_BUNDLE_ENTRIES "")
endif()
if(NOT DEFINED EXPECTED_SOURCE_ASSETS)
  set(EXPECTED_SOURCE_ASSETS "")
endif()
if(NOT DEFINED EXPECTED_PROJECT_FILES)
  set(EXPECTED_PROJECT_FILES "")
endif()
if(NOT DEFINED SOURCE_ASSETS_DIR)
  set(SOURCE_ASSETS_DIR "")
endif()
if(NOT DEFINED SOURCE_ROOT_DIR)
  set(SOURCE_ROOT_DIR "")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/NormalizeIosSdk.cmake")
platformer_normalize_ios_sdk(EXPECTED_IOS_SDK EXPECTED_IOS_SDK)
include("${CMAKE_CURRENT_LIST_DIR}/IosRequiredBundleEntries.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/IosBundledProjectFiles.cmake")

if(EXPECTED_REQUIRED_BUNDLE_ENTRIES STREQUAL "")
  list(LENGTH PLATFORMER_IOS_REQUIRED_BUNDLE_ENTRIES EXPECTED_REQUIRED_BUNDLE_ENTRIES)
endif()
if(EXPECTED_SOURCE_ASSETS STREQUAL "" AND NOT SOURCE_ASSETS_DIR STREQUAL "")
  if(NOT EXISTS "${SOURCE_ASSETS_DIR}")
    message(FATAL_ERROR "SOURCE_ASSETS_DIR does not exist: ${SOURCE_ASSETS_DIR}")
  endif()
  file(GLOB_RECURSE _source_asset_files
    LIST_DIRECTORIES false
    RELATIVE "${SOURCE_ASSETS_DIR}"
    "${SOURCE_ASSETS_DIR}/*"
  )
  list(LENGTH _source_asset_files EXPECTED_SOURCE_ASSETS)
endif()
if(EXPECTED_PROJECT_FILES STREQUAL "" AND NOT SOURCE_ROOT_DIR STREQUAL "")
  if(NOT EXISTS "${SOURCE_ROOT_DIR}")
    message(FATAL_ERROR "SOURCE_ROOT_DIR does not exist: ${SOURCE_ROOT_DIR}")
  endif()
  set(EXPECTED_PROJECT_FILES 0)
  foreach(_project_file IN LISTS PLATFORMER_IOS_BUNDLED_PROJECT_FILES)
    if(EXISTS "${SOURCE_ROOT_DIR}/${_project_file}")
      math(EXPR EXPECTED_PROJECT_FILES "${EXPECTED_PROJECT_FILES} + 1")
    endif()
  endforeach()
endif()

get_filename_component(_manifest_dir "${MANIFEST_FILE}" DIRECTORY)
set(_ipa_file "${_manifest_dir}/${APP_NAME}.ipa")
set(_ipsw_file "${_manifest_dir}/${APP_NAME}.ipsw")
set(_checksum_file "${_manifest_dir}/${APP_NAME}-ios-package-sha256.txt")
foreach(_package IN ITEMS "${_ipa_file}" "${_ipsw_file}")
  if(NOT EXISTS "${_package}")
    message(FATAL_ERROR "iOS package manifest references missing package: ${_package}")
  endif()
endforeach()
if(NOT EXISTS "${_checksum_file}")
  message(FATAL_ERROR "iOS package manifest references missing checksum file: ${_checksum_file}")
endif()

file(READ "${MANIFEST_FILE}" _manifest_text)
foreach(_fragment IN ITEMS
    "\"app_name\": \"${APP_NAME}\""
    "\"sdk\""
    "\"archs\""
    "\"device_artifact\""
    "\"code_signing_required\""
    "\"ipsw_format\": \"app_archive_compatibility_copy\""
    "\"checksum_file\": \"${APP_NAME}-ios-package-sha256.txt\""
    "\"bundle_identifier\""
    "\"bundle_short_version\""
    "\"bundle_version\""
    "\"minimum_os_version\""
    "\"validated_required_bundle_entries\""
    "\"validated_source_assets\""
    "\"validated_project_files\""
    "\"ipa\""
    "\"ipsw\""
    "\"file\": \"${APP_NAME}.ipa\""
    "\"file\": \"${APP_NAME}.ipsw\""
    "\"format_note\"")
  string(FIND "${_manifest_text}" "${_fragment}" _fragment_pos)
  if(_fragment_pos EQUAL -1)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} is missing: ${_fragment}")
  endif()
endforeach()

foreach(_metadata_key IN ITEMS
    bundle_identifier
    bundle_short_version
    bundle_version
    minimum_os_version)
  string(REGEX MATCH "\"${_metadata_key}\"[ \r\n\t]*:[ \r\n\t]*\"[^\"]+\"" _metadata_match "${_manifest_text}")
  if(_metadata_match STREQUAL "")
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} has empty or missing metadata: ${_metadata_key}")
  endif()
endforeach()

function(platformer_manifest_string_value key out_var)
  string(REGEX MATCH "\"${key}\"[ \r\n\t]*:[ \r\n\t]*\"([^\"]+)\"" _manifest_value_match "${_manifest_text}")
  if(CMAKE_MATCH_1)
    set(${out_var} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(platformer_plist_string_value plist_text key out_var)
  string(REGEX MATCH "<key>${key}</key>[ \r\n\t]*<string>([^<]+)</string>" _plist_value_match "${plist_text}")
  if(CMAKE_MATCH_1)
    set(${out_var} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

platformer_manifest_string_value("bundle_identifier" _manifest_bundle_identifier)
platformer_manifest_string_value("bundle_short_version" _manifest_bundle_short_version)
platformer_manifest_string_value("bundle_version" _manifest_bundle_version)
platformer_manifest_string_value("minimum_os_version" _manifest_minimum_os_version)
if(NOT EXPECTED_IOS_BUNDLE_IDENTIFIER STREQUAL "" AND NOT _manifest_bundle_identifier STREQUAL EXPECTED_IOS_BUNDLE_IDENTIFIER)
  message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} does not match expected bundle identifier: expected='${EXPECTED_IOS_BUNDLE_IDENTIFIER}' manifest='${_manifest_bundle_identifier}'")
endif()
if(NOT EXPECTED_IOS_MINIMUM_OS_VERSION STREQUAL "" AND NOT _manifest_minimum_os_version STREQUAL EXPECTED_IOS_MINIMUM_OS_VERSION)
  message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} does not match expected minimum OS version: expected='${EXPECTED_IOS_MINIMUM_OS_VERSION}' manifest='${_manifest_minimum_os_version}'")
endif()

set(_manifest_extract_dir "${_manifest_dir}/_validate-ios-manifest")
file(REMOVE_RECURSE "${_manifest_extract_dir}")
file(MAKE_DIRECTORY "${_manifest_extract_dir}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E tar "xf" "${_ipa_file}"
  WORKING_DIRECTORY "${_manifest_extract_dir}"
  RESULT_VARIABLE _manifest_extract_rc
  ERROR_VARIABLE _manifest_extract_err
)
if(NOT _manifest_extract_rc EQUAL 0)
  file(REMOVE_RECURSE "${_manifest_extract_dir}")
  message(FATAL_ERROR "Could not extract iOS package for manifest validation ${_ipa_file}: ${_manifest_extract_err}")
endif()
set(_manifest_info_plist "${_manifest_extract_dir}/Payload/${APP_NAME}.app/Info.plist")
if(NOT EXISTS "${_manifest_info_plist}")
  file(REMOVE_RECURSE "${_manifest_extract_dir}")
  message(FATAL_ERROR "iOS package manifest validation could not find packaged Info.plist: ${_manifest_info_plist}")
endif()
file(READ "${_manifest_info_plist}" _packaged_info_plist_text)
platformer_plist_string_value("${_packaged_info_plist_text}" "CFBundleIdentifier" _plist_bundle_identifier)
platformer_plist_string_value("${_packaged_info_plist_text}" "CFBundleShortVersionString" _plist_bundle_short_version)
platformer_plist_string_value("${_packaged_info_plist_text}" "CFBundleVersion" _plist_bundle_version)
platformer_plist_string_value("${_packaged_info_plist_text}" "MinimumOSVersion" _plist_minimum_os_version)
file(REMOVE_RECURSE "${_manifest_extract_dir}")

function(platformer_validate_manifest_metadata_matches_plist metadata_key manifest_value plist_value)
  if(plist_value STREQUAL "" OR NOT manifest_value STREQUAL plist_value)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} ${metadata_key} does not match packaged Info.plist: manifest='${manifest_value}' plist='${plist_value}'")
  endif()
endfunction()

platformer_validate_manifest_metadata_matches_plist("bundle_identifier" "${_manifest_bundle_identifier}" "${_plist_bundle_identifier}")
platformer_validate_manifest_metadata_matches_plist("bundle_short_version" "${_manifest_bundle_short_version}" "${_plist_bundle_short_version}")
platformer_validate_manifest_metadata_matches_plist("bundle_version" "${_manifest_bundle_version}" "${_plist_bundle_version}")
platformer_validate_manifest_metadata_matches_plist("minimum_os_version" "${_manifest_minimum_os_version}" "${_plist_minimum_os_version}")

if(NOT EXPECTED_IOS_SDK STREQUAL "")
  string(FIND "${_manifest_text}" "\"sdk\": \"${EXPECTED_IOS_SDK}\"" _expected_sdk_pos)
  if(_expected_sdk_pos EQUAL -1)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} does not match expected SDK: ${EXPECTED_IOS_SDK}")
  endif()
  if(EXPECTED_IOS_SDK STREQUAL "iphoneos")
    set(_expected_device_artifact_json "true")
  else()
    set(_expected_device_artifact_json "false")
  endif()
  string(FIND "${_manifest_text}" "\"device_artifact\": ${_expected_device_artifact_json}" _expected_device_artifact_pos)
  if(_expected_device_artifact_pos EQUAL -1)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} does not match expected device artifact flag: ${_expected_device_artifact_json}")
  endif()
endif()
if(NOT EXPECTED_IOS_ARCHS STREQUAL "")
  string(FIND "${_manifest_text}" "\"archs\": \"${EXPECTED_IOS_ARCHS}\"" _expected_archs_pos)
  if(_expected_archs_pos EQUAL -1)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} does not match expected archs: ${EXPECTED_IOS_ARCHS}")
  endif()
endif()
if(NOT EXPECTED_IOS_CODE_SIGNING_REQUIRED STREQUAL "")
  if(EXPECTED_IOS_CODE_SIGNING_REQUIRED)
    set(_expected_code_signing_required_json "true")
  else()
    set(_expected_code_signing_required_json "false")
  endif()
  string(FIND "${_manifest_text}" "\"code_signing_required\": ${_expected_code_signing_required_json}" _expected_signing_pos)
  if(_expected_signing_pos EQUAL -1)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} does not match expected code signing requirement: ${_expected_code_signing_required_json}")
  endif()
endif()

function(platformer_validate_manifest_count key expected_value)
  if(expected_value STREQUAL "")
    return()
  endif()
  string(FIND "${_manifest_text}" "\"${key}\": ${expected_value}" _count_pos)
  if(_count_pos EQUAL -1)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} does not match expected ${key}: ${expected_value}")
  endif()
endfunction()

platformer_validate_manifest_count("validated_required_bundle_entries" "${EXPECTED_REQUIRED_BUNDLE_ENTRIES}")
platformer_validate_manifest_count("validated_source_assets" "${EXPECTED_SOURCE_ASSETS}")
platformer_validate_manifest_count("validated_project_files" "${EXPECTED_PROJECT_FILES}")

function(platformer_validate_manifest_package package_key package_file)
  file(SIZE "${package_file}" _actual_size)
  file(SHA256 "${package_file}" _actual_sha256)
  set(_object_pattern "\"${package_key}\"[ \r\n\t]*:[ \r\n\t]*\\{[^}]*\\}")
  string(REGEX MATCH "${_object_pattern}" _object_text "${_manifest_text}")
  if(_object_text STREQUAL "")
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} is missing object: ${package_key}")
  endif()
  string(FIND "${_object_text}" "\"size_bytes\": ${_actual_size}" _size_pos)
  if(_size_pos EQUAL -1)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} has wrong size for ${package_key}")
  endif()
  string(FIND "${_object_text}" "\"sha256\": \"${_actual_sha256}\"" _sha_pos)
  if(_sha_pos EQUAL -1)
    message(FATAL_ERROR "iOS package manifest ${MANIFEST_FILE} has wrong sha256 for ${package_key}")
  endif()
endfunction()

platformer_validate_manifest_package("ipa" "${_ipa_file}")
platformer_validate_manifest_package("ipsw" "${_ipsw_file}")

file(READ "${_checksum_file}" _checksum_text)
foreach(_checksum_package IN ITEMS "ipa" "ipsw")
  if(_checksum_package STREQUAL "ipa")
    set(_checksum_package_file "${_ipa_file}")
    set(_checksum_package_name "${APP_NAME}.ipa")
  else()
    set(_checksum_package_file "${_ipsw_file}")
    set(_checksum_package_name "${APP_NAME}.ipsw")
  endif()
  file(SHA256 "${_checksum_package_file}" _checksum_package_sha256)
  string(FIND "${_checksum_text}" "${_checksum_package_sha256}  ${_checksum_package_name}" _checksum_line_pos)
  if(_checksum_line_pos EQUAL -1)
    message(FATAL_ERROR "iOS package checksum file ${_checksum_file} is missing expected checksum for ${_checksum_package_name}")
  endif()
endforeach()

file(SHA256 "${_ipa_file}" _ipa_sha256)
file(SHA256 "${_ipsw_file}" _ipsw_sha256)
if(NOT _ipa_sha256 STREQUAL _ipsw_sha256)
  message(FATAL_ERROR "iOS package IPA/IPSW hashes differ unexpectedly")
endif()

message(STATUS "Validated iOS package manifest: ${MANIFEST_FILE}")
